# Generated by Django 3.2.5 on 2021-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_rename_d_date_review_d_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='d_day',
            field=models.PositiveIntegerField(),
        ),
    ]
